### ISSUE TITLE
Re-write DumpProcessor

### ISSUE THREAD

**Issue by gamburgm** [sandboxnu/searchneu-v1#30]
# The Module
The [Dump Processor](backend/dumpProcessor.ts) inserts scraped data into the database as efficiently as possible.

# Spec
- [x] Can bulk upsert courses, sections, and professors
- [ ] Can garbage collect courses, sections, and professors
- [x] Keeps `lastUpdatedTime` for courses & sections up to date
- [ ] Can do all of the above in < 1 minute (preferably less)
- [ ] Each track can be executed independently

# Problem
- The module depends on hand-generating huge upsert query strings, making it brittle and incredibly hard to understand
- There is a lingering type error regarding sections
- There is disagreement between the Dump Processor, the scrapers, search, Prisma, and elsewhere about what courses, sections, and professors look like
- Only courses are garbage collected
- There are hotfixed bugs when the updater tries to refer to a section that has no corresponding class

# Todos
- [ ] Do a dev design
- [x] Improve/correct the types
- [ ] Create independent tracks for courses, sections and professors
- [ ] Better solution for keeping lastUpdatedTime accurate for sections
- [ ] Get rid of class
- [ ] Revamp test suite
- [ ] Document new structure

# Notes
- Use Knex.js?
    - If not, should we implement a separate bulkSQL module?
- Should garbage collection and upserting be separate components running independently? How often should we GC?
- Most, if not all, of the helper functions should be done away with--data should be correctly formed when entering the module
- there's currently no easy way to iterate over the fields of a database table in prisma, which makes constructing insert/upsert queries real clunky. Is there a way to convert schema -> value?
