### ISSUE TITLE
Migrate to GraphQL

### ISSUE THREAD

**Issue by gamburgm** [sandboxnu/searchneu-v1#37]
# Goal
GraphQL > Express

On a more serious note, the goal is multi-fold:
- Migrate to GraphQL to reduce the complexity of our API/`server` management
- Create new schema for 'Concept of a Course', Courses & Sections

A stretch goal outside the scope of this ticket (and potentially this project) is, how might users want to query for courses & catalog information and how do we express that in GraphQL?

# Todo
- [ ] Define new schema for course & section representation in GraphQL
- [ ] Create TypeDef for Search
- [ ] Invoke `searcher` module in resolvers

# Open Questions
- [ ] What do we do about the notification API and other endpoints we support?
- [ ] How are we going to integrate types & typescript into GraphQL?
