### ISSUE TITLE
Migrate to Next.js & Serverless

### ISSUE THREAD

**Issue by gamburgm** [sandboxnu/searchneu-v1#38]
# Problem
- Our API is poorly organized in the codebase
- Moving to a serverless architecture means improved developer experience & easier code review
- Cleaner division of responsibilities between `SearchNEU` and the Course Catalog information

# Solution
- Migrate to Next.js
- Separate codebase into the course component and the `SearchNEU` (User/Notifications + frontend) component

# Todo
- [ ] Move terraform, GraphQL, & other course components to separate repo
- [ ] Transform Notifications API from current state to serverless & webhook based
- [ ] Migrate frontend to Next.js

# Open Questions
- [ ] What additional challenges will there be in making this codebase pivot?
