### ISSUE TITLE
Concept of a Course

### ISSUE THREAD

**Issue by gamburgm** [sandboxnu/searchneu-v1#39]
# Goal
Search and Graduate (along with other potential tools) could benefit immensely from an API that supports the 'idea of a class', e.g. Fundies as a concept that stretches across semesters. While this can be mostly supported with the current infrastructure, there are some challenges, particularly course renamings. 

# Todos
- [ ] Create a table of aliases that connects consecutive (by semester) sets of identical courses with each other
- [ ] Create course concept API
- [ ] Modify course (concept) querying by doing deeper searches with alias table
