### ISSUE TITLE
Re-writing Modules Template

### ISSUE THREAD

**Issue by gamburgm** [sandboxnu/searchneu-v1#44]
# The Module
What is the module for?

# Spec
What must the module *do* or *support*?

# Problem
What's wrong with the module?
- What's currently unclear or overly complex?
- What doesn't live up to the spec?

# Todos
- [ ] Dev design meeting for re-write
- [ ] Correct types: add them if they're not there, sync them with existing types if they are
- [ ] Reduce complexity of the module
- [ ] Create coherent API for the module
- [ ] Add tests for each component of the module
- [ ] Document purpose of the module and its functions
- [ ] Remove class if there's no mutable state or meaningful transformations over time
