### ISSUE TITLE
Debug the Scrapers

### ISSUE THREAD

**Issue by gamburgm** [sandboxnu/searchneu-v1#45]
# Goal
The scrapers fail in two contexts:
1. on prod (always)
2. on some machines (locally)

Before we do the split, the scrapers should be back to a successful state.

# Todos
- [ ] Only scrape most recent semester(s) (for now)
- [ ] More meaningful error messages
- [ ] Identify source of slowdown & stall on local machines and on prod
- [ ] Fix those
