### ISSUE TITLE
Notification Workflow

### ISSUE THREAD

**Issue by gamburgm** [sandboxnu/searchneu-v1#50]
# Goal
Once the codebase is split, the portion of the code that sends updates to users will live in `searchneu.com`, whereas the updater component will live with the API. When the updater identifies sections or courses with open seats, that information needs to be forwarded to the remaining `searchneu.com` backend to send as actual notifications to users.

# Spec
- [ ] Create data definition for seat opening info
- [ ] Create RPC-style endpoint on `searchneu.com` side to accept it
- [ ] Send it from the modified updater on the API side
- [ ] Add some form of authentication (so that only the API side can actually hit that endpoint)

# Todo
- How will we authenticate?
